### ISSUE TITLE
internal_sensor_bandwidth' could not be set

### ISSUE THREAD

**Issue by abhishek202206** [analogdevicesinc/imu-ros2#57]
Currently I am trying to integrate ADIS16507-2 with RPI-4 and have been able to successfully read the data available on the iio_bus.

currently the way IMU is mounted on the board the y axis is pointing up so it reads the gravity value.

![Screenshot from 2024-01-11 15-24-40](https://github.com/analogdevicesinc/imu-ros2/assets/22738612/36df4fc3-55c6-43e9-95d9-5cfcee0b89ae)

so if we multiply 52997825 * 0.000000186 = 9.85759545
which is equivalent to the correct gravity value 9.8 m/s2

The issue comes when I try to run the ros2 drivers I get the same error

ubuntu@ubuntu:~/ros2_foxy$ ros2 run imu_ros2 imu_ros2_node 

mainthread 281473436934160 running...

[INFO] [1704986814.656856281] [rclcpp_main]: running: main thread

[INFO] [1704986814.663445542] [rclcpp_iiowrapper]: Found device: adis16507-2

[INFO] [1704986814.663525966] [rclcpp_iiowrapper]: Found trigger: adis16507-2-dev0

[INFO] [1704986814.666200847] [rclcpp_iiowrapper]: Read device ret_val -13 

terminate called after throwing an instance of 'rclcpp::exceptions::InvalidParameterValueException'

  what():  parameter 'internal_sensor_bandwidth' could not be set: Parameter {} doesn't comply with integer range.

The  reason which I suspect is that internal_sensor_bandwidth parameter is the parameter which is defined for the adis1650x series of ADIS IMU.

The ROS2 driver wraps IIO bus. Since the adis16507 uses adis16475.
Upon inspection of the iio_device the following parameters were found

![Screenshot from 2024-01-11 15-44-26](https://github.com/analogdevicesinc/imu-ros2/assets/22738612/9b31e0ae-3cd1-45d8-9224-0863a050b2f9)

The iio drivers doesn't have internal_bandwidth_parameter because of which when we run the ros2 driver the application is unable to find that parameter and throw this error.

**Comment by rbolboac** [comment]
Hello @abhishek202206 , please see my response in the engineer zone: https://ez.analog.com/mems/f/q-a/576710/adis16507-not-working-on-rpi-cm4-on-ubuntu-20

**Comment by abhishek202206** [comment]
Thanks @rbolboac . I am now able to stream the data on the ros2 imu node and read it correctly. Thanks 
Happy to close this issue
